finance-AI/data

- studentQA/studentQA_570_spring_2017.txt
Adding my first of 70 questions and answers.
> Adding a question

- studentQA/studentQA_570_spring_2017.txt
Submitting another question for review and learning how to use Git as well.
> Question 2 of 70

- studentQA/studentQA_570_spring_2017.txt
> Questions 3-10

- studentQA/studentQA_570_spring_2017.txt
Added question and answer #11.
> Question 11

- studentQA/studentQA_570_spring_2017.txt
> Question 12

- studentQA/studentQA_570_spring_2017.txt
> SLU - Added 15 Questions

- studentQA/studentQA_570_spring_2017.txt
> Add 10 additional questions

- studentQA/studentQA_570_spring_2017.txt
> SLU - Added 6 additional questions

- studentQA/studentQA_570_spring_2017.txt
> Adding questions 27-34.

- studentQA/studentQA_570_spring_2017.txt
> SLU-Added 13 Questions

- studentQA/studentQA_570_spring_2017.txt
Adding to my list of questions (14-26)
> Questions 14-26

- studentQA/studentQA_570_spring_2017.txt
This makes 70 questions and answers if I counted correctly.
> Adding the remainder of my questions and answers.

- studentQA/studentQA_570_spring_2017.txt
Added lines 229-278 (25 Questions)
> Update (Joseph Lopez)

- studentQA/studentQA_570_spring_2017.txt
Lines 279-368 (Chapters 11, 15, 16, 17, 19)
> JDL Update

- studentQA/studentQA_570_spring_2017.txt
> Added 26 questions

- studentQA/studentQA_480_spring_2017.txt
I have added my 40 questions and answers for the assignment
> Update to QA JoshuaToma_fin480

- studentQA/studentQA_480_spring_2017.txt
> 40 questions and answers

- studentQA/studentQA_480_spring_2017.txt
> Paul's Questions

- studentQA/studentQA_480_spring_2017.txt
my questions are from line 1054-1157
> added lines 1054-1157

- studentQA/studentQA_480_spring_2017.txt
> DamienGrandaQA_480_Spring_2017.txt.

- studentQA/studentQA_480_spring_2017.txt
Update 40 Questions and Answers
> Update 40 Questions and Answers

- studentQA/studentQA_480_spring_2017.txt
> Marissa Sheffer 40 Q&A

- studentQA/studentQA_570_winter_2017.txt
> Update Q&A 1-15

- studentQA/FIN_302_spring_2018.txt
> FIN_302_Q&A
